[global]
ioengine=libaio
direct=1
iodepth=64
rw=randwrite
bs=64k
numjobs=4
size=100%
group_reporting=1

[job1]
name=job1
filename=/dev/nvme1n1p1

[job2]
name=job2
filename=/dev/nvme1n1p2

[job3]
name=job3
filename=/dev/nvme1n1p3

[job4]
name=job4
filename=/dev/nvme1n1p4

[job5]
name=job5
filename=/dev/nvme1n1p5

[job6]
name=job6
filename=/dev/nvme1n1p6

[job7]
name=job7
filename=/dev/nvme1n1p7

[job8]
name=job8
filename=/dev/nvme1n1p8