[global]
ioengine=libaio
direct=1
iodepth=64
rw=randwrite
randseed=3072
rate=,24m
bs=4k
numjobs=2
size=100%
time_based=1
runtime=3600s
group_reporting=1

[job1]
name=job1
filename=/dev/vda

[job2]
name=job2
filename=/dev/vdb

[job3]
name=job3
filename=/dev/vdc

[job4]
name=job4
filename=/dev/vdd

[job5]
name=job5
filename=/dev/vde

[job6]
name=job6
filename=/dev/vdf

[job7]
name=job7
filename=/dev/vdg

[job8]
name=job8
filename=/dev/vdh